// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "CIA Monkey":return img`
....................
.....fffff..........
....ffeeeff.........
...ffeeeeeff........
..ffeedddeeff.......
.fffedddddefff......
.fefffffffffef......
.fedffdddffdef......
.feedddddddeef......
.ffeddededdeff..555f
.8feedddddeef8.5555.
.8ffeedfdeeff8.ee...
.88ffedddeff88.ee...
.888ffeeeff888.5....
.8888fffff8888......
..88886668888.......
.....66666..........
......442...........
.....24422..........
....2225544.........
....4445545.........
.....45524..........
......22............
.......2............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
